FROM samdobson/streamlit:0.72.0

WORKDIR /app
RUN mkdir -p /data/tmp

COPY tmp/latest.jsonl.gz /data/tmp/
COPY tmp/products.jsonl /data/tmp/
COPY stores.json /data/
COPY reporting.py ./

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "streamlit run --server.port $PORT reporting.py"]
