version: "3.8"
services:

  crawler:
    working_dir: /app
    volumes: 
      - ./:/app

  reporting:
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 8501
    ports:
      - 127.0.0.1:8501:8501

  tmp:
    image: samdobson/streamlit:0.72.0
    working_dir: /app
    command: ["tmp-02.py"]
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8502:8501
