on:
 workflow_dispatch:
 schedule:
  - cron: "0 1 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compress
      run: gzip --verbose data/$(date --date="yesterday" -u +"%Y-%m-%d").*
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: compress raw files
