on:
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_USR }}
          password: ${{ secrets.HEROKU_PWD }}
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile.reporting
          tags: registry.heroku.com/wo-ist-billy/web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: deploy
        uses: wei/curl@v1
        with:
          args: |
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer ${{ secrets.HEROKU_PWD }}"
            --netrc -X PATCH https://api.heroku.com/apps/wo-ist-billy/formation \                                                                   master 2b737bd ✗
            -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "${{ steps.docker_build.outputs.digest }}"
                }
              ]
            }'
