on:
 workflow_dispatch:
 schedule:
  - cron: "0 */1 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose -f docker-compose.yml build
    - name: crawl
      run: docker-compose -f docker-compose.yml run --entrypoint=/bin/ash app -c "scrapy crawl stock-availability -o stock-availability.jsonlines 2> /dev/null; cat stock-availability.jsonlines" >> data/stock-availablity.jsonlines
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update stock-availability
